# Generated by Django 4.0.3 on 2022-04-12 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_contract_event'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='contract',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('status__exact', False), ('event__isnull', True)), models.Q(('status__exact', True), ('event__isnull', False)), _connector='OR'), name='status_match_event'),
        ),
    ]
