# Generated by Django 4.0.3 on 2022-04-13 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='event',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='events.event'),
        ),
    ]
