# Generated by Django 4.0.3 on 2022-04-13 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0005_alter_contract_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='sales_person',
            field=models.ForeignKey(limit_choices_to={'role': 'SP'}, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
