# Generated by Django 4.0.4 on 2022-04-24 12:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0006_alter_contract_sales_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('S', 'started'), ('P', 'planned'), ('O', 'over'), ('D', 'draft')], default='D', max_length=1),
        ),
        migrations.AlterField(
            model_name='event',
            name='support_consultant',
            field=models.ForeignKey(limit_choices_to={'role': 'SC'}, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
