# Generated by Django 4.0.4 on 2022-04-22 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_remove_client_is_reachable_client_is_reachable'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='client',
            name='is_reachable',
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('email__exact', ''), _negated=True), models.Q(('phone__exact', ''), _negated=True), models.Q(('mobile__exact', ''), _negated=True), _connector='OR'), name='is_reachable'),
        ),
    ]
